# Node docker image on which this would be run
image: node:latest

cache:
  paths: 
    - node_modules/

# Pipeline:
stages:
  - build
  - deploy

# Jobs:

bundle:
  stage: build
  image: node:10.15.3
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    paths:
     - dist/

deploy_staging:
  only:
    - develop
    - master
  stage: deploy
  before_script:
    - npm install -g surge
  script:
    - cp CNAME dist
    - surge dist
    - echo "Deployed to staging server"
