cache:
  paths: 
    - node_modules/

# Pipeline:
stages:
  - build
  - deploy


# Jobs:

bundle:
  stage: build
  image: node:10.15.3
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    paths:
     - dist/

deploy_staging:
  only:
    - develop
    - master
  stage: deploy
  image: "ruby:2.5"
  script:
    # install dpl:
    - apt-get update -qy
    - apt-get install rubygems ruby-dev -y
    - gem install dpl
    # deploy to heroku:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --skip_cleanup
    - echo "Deployed to staging server"
